name: 'Unit tests'

on:
  pull_request:

env:
  TARGETS: f7
  DEFAULT_TARGET: f7
  FBT_TOOLCHAIN_PATH: /opt

jobs:
  run_units_on_bench:
    runs-on: [self-hosted, FlipperZeroIntegrationTest]
    steps:
      - name: 'Wipe workspace'
        run: find ./ -mount -maxdepth 1 -exec rm -rf {} \;

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'Flash unit tests firmware'
        id: flashing
        if: success()
        timeout-minutes: 10
        run: |
          ./fbt flash FIRMWARE_APP_SET=unit_tests FORCE=1

      - name: 'Wait for flipper and format ext'
        id: format_ext
        if: steps.flashing.outcome == 'success'
        timeout-minutes: 5
        run: |
          source scripts/toolchain/fbtenv.sh
          python3 scripts/testops.py await_flipper
          python3 scripts/storage.py format_ext

      - name: 'Copy assets and unit data, reboot and wait for flipper'
        id: copy
        if: steps.format_ext.outcome == 'success'
        timeout-minutes: 7
        run: |
          source scripts/toolchain/fbtenv.sh
          python3 scripts/testops.py await_flipper
          python3 scripts/storage.py -f send assets/resources /ext
          python3 scripts/storage.py -f send assets/unit_tests /ext/unit_tests
          python3 scripts/power.py reboot
          python3 scripts/testops.py await_flipper

      - name: 'Run units and validate results'
        id: run_units
        if: steps.copy.outcome == 'success'
        timeout-minutes: 7
        run: |
          source scripts/toolchain/fbtenv.sh
          python3 scripts/testops.py run_units

      - name: 'Check GDB output'
        if: failure()
        run: |
          ./fbt gdb_trace_all FIRMWARE_APP_SET=unit_tests FORCE=1

      - name: 'Create notification'
        if: steps.copy.outcome == 'success' && steps.run_units.outcome == 'failure'
        run: |
          echo "::Unit tests failed, check that step for details"
