name: 'Updater test'

on:
  pull_request:

env:
  TARGETS: f7
  DEFAULT_TARGET: f7
  FBT_TOOLCHAIN_PATH: /opt

jobs:
  test_updater_on_bench:
    runs-on: [self-hosted, FlipperZeroIntegrationTest]
    steps:
      - name: 'Wipe workspace'
        run: find ./ -mount -maxdepth 1 -exec rm -rf {} \;

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: false
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'Flashing target firmware'
        id: first_full_flash
        timeout-minutes: 10
        run: |
          source scripts/toolchain/fbtenv.sh
          ./fbt flash_usb_full FORCE=1
          python3 scripts/testops.py await_flipper

      - name: 'Validating updater'
        id: second_full_flash
        timeout-minutes: 5
        run: |
          source scripts/toolchain/fbtenv.sh
          ./fbt flash_usb_full FORCE=1
          python3 scripts/testops.py await_flipper

      - name: 'Create notification'
        if: failure()
        run: |
          echo "::error ::Flipper updater failure"

